export const paths = {
  dashboard: '/',
  herd: '/rodeos',
  animalFicha: '/rodeos/:id',
  events: '/eventos',
  agenda: '/agenda',
  clients: '/clientes',
  sales: '/ventas',
  feed: '/alimentacion',
  production: '/produccion',
  vaccination: '/vacunacion',
  settings: '/configuracion',
  users: '/usuarios',
  profile: '/perfil',
  changePassword: '/cambiar-password',
  login: '/login',
} as const;
