import { Router } from 'express';
import { agendaRouter } from './agenda.routes';
import { alimentacionRouter } from './alimentacion.routes';
import { animalesRouter } from './animales.routes';
import { asistenteRouter } from './asistente.routes';
import { authRouter } from './auth.routes';
import { clientesRouter } from './clientes.routes';
import { configuracionRouter } from './configuracion.routes';
import { dashboardRouter } from './dashboard.routes';
import { eventosRouter } from './eventos.routes';
import { healthRouter } from './health.routes';
import { lotesRouter } from './lotes.routes';
import { notificacionesRouter } from './notificaciones.routes';
import { produccionRouter } from './produccion.routes';
import { usersRouter } from './users.routes';
import { vacunacionRouter } from './vacunacion.routes';
import { ventasRouter } from './ventas.routes';

export const routes = Router();

routes.use(healthRouter);
routes.use(authRouter);
routes.use(asistenteRouter);
routes.use(dashboardRouter);
routes.use(clientesRouter);
routes.use(configuracionRouter);
routes.use(alimentacionRouter);
routes.use(animalesRouter);
routes.use(eventosRouter);
routes.use(agendaRouter);
routes.use(vacunacionRouter);
routes.use(produccionRouter);
routes.use(ventasRouter);
routes.use(lotesRouter);
routes.use(notificacionesRouter);
routes.use(usersRouter);
